config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  
  get 'sessions/create'

  get 'sessions/destroy'

  get 'character/index'

  resources :parties
  resources :characters

  get 'user/create'
  
  get 'welcome/index'
  
  get 'welcome/signup'
  
  get 'welcome/profile'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :memberships       #Has many memberships that define the relationship between characters and parties
    has_many :parties, through: :memberships
    belongs_to :user        #Owned by a user model
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :party       #Owned by parties and characters, defines the relationship between them
    belongs_to :character
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :memberships           #Has many memberships that define the associations with characters
    has_many :characters, through: :memberships 
    belongs_to :user        #Owned by the user model
end

app/models/user.rb
# The Omniauth google is working to save things to User model

class User < ApplicationRecord
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
          user.provider = auth.provider
          user.uid = auth.uid                               #Fetches values from Google Authentication
          user.name = auth.info.name
          user.oauth_token = auth.credentials.token
          user.oauth_expires_at = Time.at(auth.credentials.expires_at)
          user.save!
        end
    end
    has_many :characters        #Ownes characters and parties
    has_many :parties
end

app/controllers/application_controller.rb
# Prevent attacks by raising an exception.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user #Defines helper method to return the user currenting in the app

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #Fetches the user logged in now
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  def index
    @characters = Character.all  #Fetch all characters
  end
  
  def show
    @character = Character.find(params[:id]) #Find character based on character attributes
  end
  
  # GET /characters/new
  def new
    @character = Character.new
  end
  # POST /characters
  def create
    @user = current_user   #Define current user
    @character = @user.characters.create(character_params)   #Create a new character belonging to the current user
    
    if @character.save
      redirect_to @character  #redirect to show character
    else
      render 'new'
    end
  end
  
  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])   #Find character based on character attributes
  end
    
  def update
    @character = Character.find(params[:id])   #Find character based on character attributes
    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end
   # DELETE /characters/1
  def destroy
    @user = current_user   #Define current user
    @character = @user.characters.find(params[:id])   #Find the character that belongs to the current user with the given parameters
    @character.destroy    #Remove the character
    
    redirect_to characters_path
  end
end

private
  def character_params                #Character parameters that are inputted by the user
    params.require(:character).permit(:name, :race, :klass, :vitality, :strength, :agility, :arcane, :resistance, :stamina)
  end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
    #Access current_user in model


    def create
        @user = current_user    #Define current user
        @party = @user.parties.create(party_params)   #Create a new party belonging to the current user
        @characters = Character.where(:id => params[:characters_ids])  #Find characters based on their character ID's
        @party.characters << @characters    #Add those characters to the party's list of characters
        
        if @party.save
          redirect_to @party
        else
          render 'new'
        end
    end
    
    def index
        @parties = Party.all
    end
    
    def new
        @user = current_user
        @party = Party.new
    end
    
    def show
        @party = Party.find(params[:id])
        @characters = Character.includes(:parties).where(parties: {id: @party.id})   #Finds alls of the characters in the party 
    end
    
    def edit
        @party = Party.find(params[:id])
        @user = current_user
    end
    
    def update
        @party = Party.find(params[:id])
        if @party.update(party_params)    #Finds and updates the party object
            redirect_to @party
        else
            render 'edit'
        end
    end
    
    def destroy
        @user = current_user
        @party = @user.parties.find(params[:id])   #Find the party among the parties the user has
        @party.destroy
        
        redirect_to parties_path
    end
end

private
    def party_params                #Define party parameters, accepts an array of character ID's to assign to the party
        params.require(:party).permit(:name, character_ids:[])
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#Create a sessions 
  def create
    user = User.from_omniauth(request.env["omniauth.auth"]) #Gets Google authentication
    session[:user_id] = user.id   #Creates a session for the user
    redirect_to root_path
  end
# destroy session
  def destroy
    session[:user_id] = nil   #Ends the session on sign out
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
#OLD USER CONTROLLER, FUNCTIONS HERE ARE NOT USED
class UserController < ApplicationController
  # GET /users/1
  def show
    @user = User.find(params[:id])
  end
  # GET /users/new
  def new
    @user = User.new
  end
   # POST /users
  def create
    @user = User.new(user_params())
    
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def index
  end
end

private
  def user_params
    params.require(:user).permit(:uname, :psw, :chalist)
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_character.html.erb
<p>
    <%= character.name %>
</p>

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>
    
    <% if @character.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@character.errors.count, "error") %> prohibited this article from being saved:
        </h2>
        <ul>
            <% @character.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</p>
<!--Type of Race-->
<p>
    <%= f.label :race %>
    <%= f.select(:race, ['Human', 'Elf', 'Orc', 'Undead', 'Dwarf', 'Pixie'], {}, { :class => 'characters' }) %>
</p>
<!--Labels-->
<p>
    <%= f.label :class %>
    <%= f.select(:klass, ['Wizard', 'Brawler', 'Gunslinger', 'Thief', 'Cleric', 'Healer', 'Ranger'], {}, { :class => 'characters' }) %>
</p>
<!--Setting size of number of field-->
<p>
    <%= f.label :Vitality %>
    <%= f.number_field(:vitality, in: 1..10) %>
</p>

<p>
    <%= f.label :Strength %>
    <%= f.number_field(:strength, in: 1..10) %>
</p>

<p>
    <%= f.label :Agility %>
    <%= f.number_field(:agility, in: 1..10) %>
</p>

<p>
    <%= f.label :Arcane %>
    <%= f.number_field(:arcane, in: 1..10) %>
</p>

<p>
    <%= f.label :Resistance %>
    <%= f.number_field(:resistance, in: 1..10) %>
</p>

<p>
    <%= f.label :Stamina %>
    <%= f.number_field(:stamina, in: 1..10) %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/characters/edit.html.erb
<!--Link back to page visited before form-->
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Back', character_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<p><center><%= link_to 'New character', new_character_path %></center></p>

<table style="height:100%" class="darkTable">
    <!--Table all of the list characters-->
    <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Class</th>
        <th>Vitality</th>
        <th>Strength</th>
        <th>Agility</th>
        <th>Arcane</th>
        <th>Resistance</th>
        <th>Stamina</th>
        <th colspan="3">Options</th>
    </tr>
    
    <% current_user.characters.each do |character| %>
    <tr>
        <td><%= character.name %></td>
        <td><%= character.race %></td>
        <td><%= character.klass %></td>
        <td><%= character.vitality %></td>
        <td><%= character.strength %></td>
        <td><%= character.agility %></td>
        <td><%= character.arcane %></td>
        <td><%= character.resistance %></td>
        <td><%= character.stamina %></td>
        <td><%= link_to 'Show', character_path(character) %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character_path(character), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

<br>
<center><%= link_to 'Party List', parties_path %></center>

app/views/characters/new.html.erb
<!--linking to the form for to add new characters-->
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<!--added character controller-->
<div id="charshow">
<p>
    Name:
    <%= @character.name %>
    <nav id="pic">
    <%= image_tag("Backgrounds/mage.jpg", :alt => "rss feed", size: "275x200") %>
    </nav>
</p>

<p>
    Race:
    <%= @character.race %>
</p>

<p>
    Class:
    <%= @character.klass %>
</p>

<p>
    <strong><u>Stats</u></strong><br>
</p>
<p>
    Vitality:<%= @character.vitality %> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp  Arcane:<%= @character.arcane %><br>
    Strength:<%= @character.strength %> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Resistance:<%= @character.resistance %><br>
    Agility:<%= @character.agility %> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp   Stamina:<%= @character.stamina %><br>
</p>




<center><%= link_to 'Character List', characters_path %></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RPG Generator</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="loginn">
      <% if current_user %>
        <strong><%= current_user.name %></strong>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/parties/_form.html.erb
<div id="parshow">
<%= form_for @party do |f| %>

<% if @party.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@party.errors.count, "error") %> prohibited this article from being saved:
        </h2>
        <ul>
            <% @party.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
</p>

<p>Select characters to add:</p>
<table class="darkTable">
    <tr>
        <th></th>
        <th>Name</th>
        <th>Race</th>
        <th>Class</th>
    </tr>
    <%= hidden_field_tag "party[character_ids][]", nil %>
    <%= @user.characters.find_each do |character| %>

    <tr>
        <td><%= check_box_tag "party[character_ids][]", character.id, @party.character_ids.include?(character.id), id: dom_id(character) %></td>
        <td><%= label_tag dom_id(character), character.name %></td>
        <td><%= character.race %></td>
        <td><%= character.klass %></td>
    </tr>
    <% end %>
    </table>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>
</div>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Back', party_path %>

app/views/parties/index.html.erb
<h1>Listing Parties</h1>

<p><center><%= link_to 'New party', new_party_path %></p></center>

<center><table style="width:39%" class="darkTable">
    <tr>
        <th>Name</th>
        <th>Members</th>
        <th colspan="3">Options</th>
    </tr>
    
    <% current_user.parties.each do |party| %>
    <tr>
        <td><%= party.name %></td>
        <td>
            <%= party.characters.find_each do |character| %>
            <%= character.name %>
            <br>
            <% end %>
        </td>
        <td><%= link_to 'Show', party_path(party) %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party_path(party), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </td>
    </tr>
    <% end %>
</table>
<br>
<%= link_to 'Character List', characters_path %>
</center>

app/views/parties/new.html.erb
<h1>New Party</h1>


<%= render 'form' %>

app/views/parties/show.html.erb
<div id="parshow"><center>
<h1>
    Party Name:
    <%= @party.name %>
</h1>

<p>Party Members:</p>
    <%= @party.characters.find_each do |character| %>
<p>
    <%= character.name %>
</p>

    <% end %></center>
    
<%= link_to 'Party List', parties_path %>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1>RPG Character Customizer</h1>

<p>Hello, and welcome to Gem Bundle's 3155 project, RPG Character Custimization. In this web application, you will be able to create, delete, and view characters. You can even
allocate skill points to upgrade your character and make them stronger!</p>
<!--navagation bar has 3 button for user create, delete, view-->
<div class="nav">
    <!--Buttons for create, delete and view buttons-->
<button type="button">Create</button>
<button type="button">Delete</button>
<button type="button">View</button>
</div>
<!--pulling image form for UI-->
<div>
<img src="warrior.png" alt="warrior" height="42" width="42">
<img src="mage.png" alt="mage" height="42" width="42">
<img src="archer" alt="archer" height="42" width="42">
</div>

app/views/welcome/index.html.erb
<h1 class="title">
    RPG Generator
</h1>

<!--
<!--div tag to get style for login-->
<!--
<div class="login">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>
<!--takes input from the user for username and password
    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <center><a href="welcome/profile"><button>Login</button></a></center>
    <center><a href="welcome/signup"><button>Signup</button></a></center>

</div>
-->

<body>
    <div class="login">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    <%= yield %>
    </div>

 <center>
     <%= image_tag("Backgrounds/google.png", :size => "50x50", :alt => "logo") %>

<br>
<br>
<%= link_to 'Character List', characters_path %>
<br>
<%= link_to 'Party List', parties_path %>
</center>
  </body>

app/views/welcome/profile.html.erb
<<<<<<< HEAD
<<<<<<< HEAD
<h1>Listing characters</h1>
<%= link_to 'New character', new_character_path %>
<table>
    <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Class</th>
    </tr>
    
    <% @characters.each do |article| %>
    <tr>
        <td><%= character.name %></td>
        <td><%= character.race %></td>
        <td><%= character.klass %></td>
        <td><%= link_to 'Show', character_path(character) %></td>
    </tr>
</table>
=======
<!--adding raws and columns to the table-->
<div class="divTable darkTable">
=======
<div class="divTable minimalistBlack">
>>>>>>> frontend
<div class="divTableHeading">
<div class="divTableRow">
<div class="divTableHead">Race</div>
<div class="divTableHead">Class</div>
<div class="divTableHead">Vitality</div>
<div class="divTableHead">Strength</div>
<div class="divTableHead">Agility</div>
<div class="divTableHead">Arcane</div>
<div class="divTableHead">Resistance</div>
<div class="divTableHead">Resistance</div>
</div>
</div>
<div class="divTableBody">
<div class="divTableRow">
<div class="divTableCell">Human</div>
<div class="divTableCell">Wizard</div>
<div class="divTableCell">cell3_1</div>
<div class="divTableCell">cell4_1</div>
<div class="divTableCell">cell5_1</div>
<div class="divTableCell">cell6_1</div>
<div class="divTableCell">cell7_1</div>
<div class="divTableCell">cell8_1</div>
</div>
<div class="divTableRow">
<div class="divTableCell">Orc</div>
<div class="divTableCell">Brawler</div>
<div class="divTableCell">cell3_2</div>
<div class="divTableCell">cell4_2</div>
<div class="divTableCell">cell5_2</div>
<div class="divTableCell">cell6_2</div>
<div class="divTableCell">cell7_2</div>
<div class="divTableCell">cell8_2</div>
</div>
<div class="divTableRow">
<div class="divTableCell">Elf</div>
<div class="divTableCell">Gunslinger</div>
<div class="divTableCell">cell3_3</div>
<div class="divTableCell">cell4_3</div>
<div class="divTableCell">cell5_3</div>
<div class="divTableCell">cell6_3</div>
<div class="divTableCell">cell7_3</div>
<div class="divTableCell">cell8_3</div>
</div>
<div class="divTableRow">
<div class="divTableCell">Undead</div>
<div class="divTableCell">Thief</div>
<div class="divTableCell">cell3_4</div>
<div class="divTableCell">cell4_4</div>
<div class="divTableCell">cell5_4</div>
<div class="divTableCell">cell6_4</div>
<div class="divTableCell">cell7_4</div>
<div class="divTableCell">cell8_4</div>
</div>
<div class="divTableRow">
<div class="divTableCell">Dwarf</div>
<div class="divTableCell">Healer</div>
<div class="divTableCell">cell3_5</div>
<div class="divTableCell">cell4_5</div>
<div class="divTableCell">cell5_5</div>
<div class="divTableCell">cell6_5</div>
<div class="divTableCell">cell7_5</div>
<div class="divTableCell">cell8_5</div>
</div>
</div>
</div>
>>>>>>> 6b9619cccdb4aab9ca9fda1f2b9e8b882ca5a5ac

app/views/welcome/show.html.erb
<!--added create and delete button -->
<div class="nav">
    <button type="button">Create</button>
    <button type="button">Delete</button>
</div>

<body>
  <!--creating the table for items-->
  <div id="firsttablediv">
    <table id="firsttable" border="1">
      <thead>
        <th>Item</th>
        <th colspan="3">Filling</th>
        <th>Storage</th>
        <th>Minimum Stock</th>
        <th>Last Inventory</th>
        <th>Sell</th>
        <th>Last Month Inventory</th>
        <th colspan="2">
          <button id="insertitem">New Item</button>
        </th>
      </thead>
      <tbody id="insertfirsttable">
      </tbody>
    </table>
  </div>

app/views/welcome/signup.html.erb
<h1>Sign Up Page</h1>

<p>Fill out the information below to get your account created!</p>
<!--getting user input for signup page from the user for i.e. first name, last name username etc -->
<form>
    <label><b>First Name: </b></label>
    <input type="text" placeholder="First Name" name="firstname" required>
    
    <label><b>Last Name: </b></label>
    <input type="text" placeholder="Last Name" name="lastname" required>
    
    <label><b>Username: </b></label>
    <input type="text" placeholder="Username" name="username" required>
    
    <label><b>Password: </b></label>
    <input type="password" placeholder="Password" name="password" required>
    
    <label><b>Email: </b></label>
    <input type="text" placeholder="Email" name="email" required>
    
    <button type="submit" class="signup">Sign Up</button>

</form>